# Generated by Django 3.1.7 on 2021-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='respondido',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
