# Generated by Django 3.1.7 on 2021-02-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateField()),
                ('data_publicacao', models.DateField()),
                ('ativo', models.BooleanField()),
                ('autor', models.ForeignKey(default='Anônimo', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(default='Sem categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='artigo.categoria')),
            ],
        ),
    ]
